# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
---
version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.9.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: update yarn
          command: sudo npm install yarn@1.3.2 --global
      - restore_cache:
          keys:
            - v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: run linters
          command: yarn lint

  test:
    docker:
      - image: circleci/node:8.9.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: update yarn
          command: sudo npm install yarn@1.3.2 --global
      - restore_cache:
          keys:
            - v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-node_modules-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: run tests
          command: yarn test --maxWorkers 2

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test
